name: Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      tag_id:
        description: 'give a tag ID here'
        required: true
        default: ''

jobs:
  deploy:
    environment: Test_DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Get package version
        id: get_version
        run: echo "version=$(node -p -e "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Deploy application
        env:
          TAG: ${{ github.ref }}
        run: |
          echo "Deploying version $TAG"
          echo "Contents of index.html:"
          cat index.html

         

      - name: Notify deployment success
        run: echo "Deployment of version $TAG completed successfully."
