name: Tagging Workflow

on:
  push:
    branches:
      - main

jobs:
  tag-version:
    environment: Test_DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Get package version
        id: get_version
        run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"

      - name: Create tag
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --global user.email "cokasomeshrao@outlook.com"
          git config --global user.name "SomeshRao007"
          git tag $VERSION
          git push origin $VERSION
