name: Tagging Workflow
on:
  push:
    branches:
      - main
jobs:
  tag-version:
    environment: Test_DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
      
      - name: Get package version
        id: get_version
        run: echo "version=$(node -p -e "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Debug information
        run: |
          git remote -v
          git branch
          git status
      
      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          VERSION=${{ steps.get_version.outputs.version }}
          git tag $VERSION
          git push origin $VERSION
