name: Tagging Workflow

on:
  push:
    branches:
      - main

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Get package version
        id: get_version
        run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"

      - name: Create tag
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          # git config --global user.email "your-email@example.com"
          # git config --global user.name "your-github-username"
          # git tag $VERSION
          # git push origin $VERSION
